spring.application.name=demo
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration# spring.datasource.url=http://localhost:8080/bonjour
# spring.datasource.username=user1
# spring.datasource.password=pass
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
